### ISSUE TITLE
Traceback in Control-C

### ISSUE THREAD

**Issue by rec** [rec/recs#109]
```Traceback (most recent call last):
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/threa/thread.py", line 120, in run
    self.callback()
  File "/Users/tom/synthetic/code/recs/recs/ui/recorder.py", line 56, in set_devices
    self.devices = device.input_names()
  File "/Users/tom/synthetic/code/recs/recs/cfg/device.py", line 111, in input_names
    return sorted(str(i['name']) for i in query_devices())
  File "/Users/tom/synthetic/code/recs/recs/cfg/device.py", line 106, in query_devices
    r = sp.run((sys.executable, '-c', P), text=True, check=True, stdout=sp.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/Users/tom/synthetic/code/recs/.direnv/python-3.10/bin/python', '-c', 'import json,
sounddevice; print(json.dumps(sounddevice.query_devices(), indent=4))')' returned non-zero exit status 1.
```

**Comment by rec** [comment]
I'm going to bandage this right now but in general, I should look again at the `stop`/`__exit__` sequence, I must have broken this...

**Comment by rec** [comment]
Nope, there's a new one now:

```
 File "<string>", line 1, in <module>
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 55, in <module>
    import platform as _platform
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/platform.py", line 1259, in <module>
    _os_release_unescape = re.compile(r"\\([\\\$\"\'`])")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 303, in _compile
```

This doesn't entirely make sense, but I'm morally certain it's the same  `stop`/`__exit__ ` thing...

**Comment by rec** [comment]
Arg!


```
└─────────────┴────────────────────────┴─────────┴────┴─────────────┴───────────┴────────────┴────────┘^CTraceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 332, in _bootstrap
    return self._bootstrap(parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 332, in _bootstrap
    return self._bootstrap(parent_sentinel)

```

**Comment by rec** [comment]
And this other one:

```
  File "<string>", line 1, in <module>
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 2871, in <module>
    _initialize()
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 2835, in _initialize
    _check(_lib.Pa_Initialize(), 'Error initializing PortAudio')
KeyboardInterrupt
```

**Comment by rec** [comment]
Aha, it's because I'm not reading for the stop message in the child process! I need a new thread and all...

**Comment by rec** [comment]
Astonishingly, this is still in progress, but I have revamped and simplified the message passing and I feel I'm... closer.

Were there a way to just suppress these errors, I'd have done it a while ago...
