### ISSUE TITLE
`recs -u pcm_24` crashes

### ISSUE THREAD

**Issue by rec** [rec/recs#91]
```
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x11ad85a20>:
Traceback (most recent call last):
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 843, in callback_ptr
    data = _array(
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 2703, in _array
    data = np.frombuffer(buffer, dtype=dtype)
TypeError: data type <SdType.int24: 'int24'> not understood
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x11ad85cf0>:
Traceback (most recent call last):
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 843, in callback_ptr
    data = _array(
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 2703, in _array
    data = np.frombuffer(buffer, dtype=dtype)
TypeError: data type <SdType.int24: 'int24'> not understood
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x11ad85bd0>:
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x11ad85e10>:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 843,
in callback_ptr
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 843,
in callback_ptr
    data = _array(
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 2703,
in _array
    data = _array(
    data = np.frombuffer(buffer, dtype=dtype)
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/sounddevice.py", line 2703,
in _array
TypeError: data type <SdType.int24: 'int24'> not understood
    data = np.frombuffer(buffer, dtype=dtype)
TypeError: data type <SdType.int24: 'int24'> not understood
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━┓
┃ time        ┃ device                 ┃ channel ┃ on ┃ recorded ┃ file_size ┃ file_count ┃ volume ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━┩
│      15.991 │                        │         │    │          │           │ 0          │        │
│             │ FLOW 8 (Recording)     │         │ ˣ  │          │           │            │        │
│             │                        │ 1-2     │ ˣ  │          │           │ 0          │        │
│             │                        │ 3-4     │ ˣ  │          │           │ 0          │        │
│             │                        │ 5-6     │ ˣ  │          │           │ 0          │        │
│             │                        │ 7-8     │ ˣ  │          │           │ 0          │        │
│             │                        │ 9-10    │ ˣ  │          │           │ 0          │        │
│             │ USB PnP Sound Device   │         │ ˣ  │          │           │            │        │
│             │                        │  1      │ ˣ  │          │           │ 0          │        │
│             │ MacBook Pro Microphone │         │ ˣ  │          │           │            │        │
│             │                        │  1      │ ˣ  │          │           │ 0          │        │
│             │ ZoomAudioDevice        │         │ ˣ  │          │           │            │        │
│             │                        │ 1-2     │ ˣ  │          │           │ 0          │        │
└─────────────┴────────────────────────┴─────────┴────┴──────────┴───────────┴────────────┴────────┘
```

**Comment by rec** [comment]
We need to be able to record in 24-bit - if this isn't the way, we need a graceful error and a hint as to what to do.

(I did get 24-bit recording working before...)

**Comment by rec** [comment]
No, I got 24-bit output!  

There is no way to do the numpy input stuff with 24-bit audio, it only works for "raw" (pure Python) input which is far too slow.

I'm removing the whole int24 possibility.
