### ISSUE TITLE
Some filetypes crash on setting metadata

### ISSUE THREAD

**Issue by rec** [rec/recs#93]
```
$ recs -u pcm_24 -f raw -d int32

Traceback (most recent call last):
  File "/Users/tom/synthetic/code/recs/recs/cfg/device.py", line 64, in cb
    callback(indata.copy(), stream._recs_timestamp)
  File "/Users/tom/synthetic/code/recs/recs/ui/device_recorder.py", line 52, in callback
    c.callback(array, time)
  File "/Users/tom/synthetic/code/recs/recs/ui/channel_recorder.py", line 26, in callback
    self.writer.write(b, time)
  File "/Users/tom/synthetic/code/recs/recs/audio/channel_writer.py", line 95, in write
    self._write(block, dt)
  File "/Users/tom/synthetic/code/recs/recs/audio/channel_writer.py", line 112, in _write
    self._write_blocks(self._blocks)
  File "/Users/tom/synthetic/code/recs/recs/audio/channel_writer.py", line 150, in _write_blocks
    self._write_one(b)
  File "/Users/tom/synthetic/code/recs/recs/audio/channel_writer.py", line 159, in _write_one
    self._sf = self.opener.create(metadata, self.timestamp, index)
  File "/Users/tom/synthetic/code/recs/recs/audio/file_opener.py", line 44, in create
    return self.open(f, metadata)
  File "/Users/tom/synthetic/code/recs/recs/audio/file_opener.py", line 31, in open
    setattr(fp, k, v)
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/soundfile.py", line 731, in __setattr__
    _error_check(err)
  File "/Users/tom/synthetic/code/recs/.direnv/python-3.10/lib/python3.10/site-packages/soundfile.py", line 1407, in _error_check
    raise LibsndfileError(err, prefix=prefix)
soundfile.LibsndfileError: Error : File type does not support string data.
```

**Comment by rec** [comment]
This also hangs the process!

So, it will good to understand why this doesn't work, and see if I can eliminate the hang before I eliminate the crash.
